from db.db_config import DB_CONFIG
from fetch.fetch_goals_fact import fetch_goals_fact
from extract.extract_counters import extract_counters
from transform.filter_goals_fact import filter_goals_fact
from save.save_goals_fact_to_db import save_goals_fact_to_db
from extract.extract_tracking_goals_info import extract_tracking_goals_info

counters = extract_counters(DB_CONFIG)
all_goals_fact = fetch_goals_fact(counters)
tracking_goals_info = extract_tracking_goals_info(DB_CONFIG)
filtered_goals_fact = filter_goals_fact(all_goals_fact, tracking_goals_info)
save_goals_fact_to_db(DB_CONFIG, filtered_goals_fact)